### ISSUE TITLE
Faster solution instead of array_unique()

### ISSUE THREAD

**Issue by rvadym** [paljinov/php-codility#1]
Ticket is related to this [solution](https://github.com/paljinov/php-codility/blob/master/Lesson%2004%20-%20Sorting/Distinct.php)    

```
// this can be also solved with 
// return count(array_unique($A));
```

This is result with array_unique()
https://codility.com/demo/results/demoATDHG8-X7Z/
Only 66% for Performance

But according to this [article](http://www.puremango.co.uk/2010/06/fast-php-array_unique-for-removing-duplicates/) this task can be solved with native php functions keeping good Performance score

```
return count(array_flip(array_flip(array_reverse($A,true))));
```

;)

**Comment by paljinov** [comment]
I've tested **array_unique** approach.
I am getting 100/100, and obviously you got 100/66, only different thing is input, which is larger in your case, so the time is slower. With growing array $A your native function use is increasingly better solution. Why this is the case, is explained in the link that you've provided.

Problematic test is **large_random1** _chaotic sequence of values from [-1M..1M], length=100K_:

| SOLUTION | Time | Link |
| --- | --- | --- |
| count(array_unique($A)) - YOU | 0.944 s | https://codility.com/demo/results/demoATDHG8-X7Z/ |
| count(array_unique($A)) - ME | 0.516 s | https://codility.com/demo/results/demoGCBB35-KFJ/ |
| count(array_flip(array_flip(array_reverse($A,true))) | 0.204 s | https://codility.com/demo/results/demo8C3NFT-2D5/ |
| MY CUSTOM CODE | 0.320 s | https://codility.com/demo/results/demo8CTQH9-EF6/ |

Please, can you push your solution, just change:

```
// this can be also solved with 
// return count(array_unique($A));
```

in 

```
// this can be also solved with 
// return count(array_flip(array_flip(array_reverse($A, true))));
```
