### ISSUE TITLE
Pomoć/Help

### ISSUE THREAD

**Issue by mbaric** [paljinov/php-codility#7]
Pozdrav majstore,

I will write further in ENG so other people can understand too. Today I was on technical interview. Got 3 tasks. 1st I got 100%. 2nd and 3rd I tried with no luck. I hope you can help me out here.

1. Task 1
Text: https://pastebin.com/F8D77snE
Solution: https://pastebin.com/QgNfbhZz

2. Task 2
Text: https://pastebin.com/7cPdLr5K

3. Task 3
Text: https://pastebin.com/CMmAyQEZ

**Please help me out.** Thanks

**Comment by paljinov** [comment]
Hi,

I'm seeing this too late, I hope that technical interview passed well for you. As these tasks are not in the domain of this repository, I will close the issue.
